### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Kimthanh27** [Haoming02/sd-webui-old-photo-restoration#10]
I would like to ask about this recurring error. I have the correct model and placed it in two folders: "face detection" and "face enhancement." I placed it in the "checkpoints" folder, but one of the two folders doesn't have this folder when I cloned it using Git. I also created the "checkpoints" folder myself and placed the model in it. However, I still cannot perform image restoration and receive the error message "'NoneType' object is not subscriptable.
thanks and looking forward to hearing from you soon

**Comment by Haoming02** [comment]
When you launch the Webui, is there a warning about missing models?
