### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Nelayme** [Haoming02/sd-webui-old-photo-restoration#11]
I've followed all the steps, downloaded all the files, and extracted them to the correct folders. Also, I set the actual path to the folder where the image is, but whenever I press to generate, it gives me "Bruh..." in the console. I'm not getting any errors on startup, so I wonder if I missed something or if it just doesn't work for me.
I'm on ForgeUI

**Comment by Haoming02** [comment]
Oh. It prints “Bruh” when your input and output paths are the same XD

**Comment by Nelayme** [comment]
I had thought it might be an issue just before your reply, lol. Thanks, I'll try again later today.
