### ISSUE TITLE
Can't install, because (at least) dlib cannot be installed.

### ISSUE THREAD

**Issue by itzolkmar** [Haoming02/sd-webui-old-photo-restoration#12]
I use the one-click-version of AUTO1111 1.8 with NVIDIA RTX 3080 TI GPU on Windows 11.

Here's the start log: 

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Installing fastai==1.0.60 for DeOldify extension
*** Error running install.py for extension <AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration.
*** Command: "<AUTO1111-1.8-path>\system\python\python.exe" "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\install.py"
*** Error code: 1
*** stdout:
*** Installing Requirements for Bringing-Old-Photos-Back-to-Life...
*** Installing Old-Photo-Restoration Requirement: dlib
***
*** stderr: Traceback (most recent call last):
***   File "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\install.py", line 19, in <module>
***     launch.run_pip(f"install {package}", f"Old-Photo-Restoration Requirement: {package}")
***   File "<AUTO1111-1.8-path>\webui\modules\launch_utils.py", line 143, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "<AUTO1111-1.8-path>\webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install Old-Photo-Restoration Requirement: dlib.
*** Command: "<AUTO1111-1.8-path>\system\python\python.exe" -m pip install dlib --prefer-binary
*** Error code: 2
*** stdout: Collecting dlib
***   Downloading dlib-19.24.2.tar.gz (11.8 MB)
***      --------------------------------------- 11.8/11.8 MB 40.9 MB/s eta 0:00:00
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***
*** stderr: ERROR: Exception:
*** Traceback (most recent call last):
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
***     status = run_func(*args)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
***     return func(self, options, args)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
***     requirement_set = resolver.resolve(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
***     result = self._result = resolver.resolve(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
***     state = resolution.resolve(requirements, max_rounds=max_rounds)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
***     self._add_to_criteria(self.state.criteria, r, parent=None)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
***     if not criterion.candidates:
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
***     return bool(self._sequence)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
***     return any(self)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
***     return (c for c in iterator if id(c) not in self._incompatible_ids)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
***     candidate = func()
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
***     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
***     self._link_candidate_cache[link] = LinkCandidate(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
***     super().__init__(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
***     self.dist = self._prepare()
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
***     dist = self._prepare_distribution()
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
***     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
***     return self._prepare_linked_requirement(req, parallel_builds)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
***     dist = _get_prepared_distribution(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
***     abstract_dist.prepare_distribution_metadata(
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
***     self._install_build_reqs(finder)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
***     build_reqs = self._get_build_requires_wheel()
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
***     return backend.get_requires_for_build_wheel()
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 745, in get_requires_for_build_wheel
***     return super().get_requires_for_build_wheel(config_settings=cs)
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
***     return self._call_hook('get_requires_for_build_wheel', {
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
***     raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
***   File "<AUTO1111-1.8-path>\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
***     obj = import_module(mod_path)
***   File "importlib\__init__.py", line 126, in import_module
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<AppData path>\Local\Temp\pip-build-env-945bz07d\overlay\Lib\site-packages\setuptools\__init__.py", line 14, in <module>
***     from . import version as _version_module
***   File "<AppData path>\Local\Temp\pip-build-env-945bz07d\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
***     from ._importlib import metadata
***   File "<AppData path>\Local\Temp\pip-build-env-945bz07d\overlay\Lib\site-packages\setuptools\_importlib.py", line 45, in <module>
***     import importlib.metadata as metadata  # noqa: F401
***   File "importlib\metadata\__init__.py", line 17, in <module>
***   File "importlib\metadata\_adapters.py", line 3, in <module>
***   File "email\message.py", line 15, in <module>
***   File "email\utils.py", line 29, in <module>
***   File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
***
Launching Web UI with arguments: --medvram --opt-sdp-no-mem-attention --disable-safe-unpickle --listen --enable-insecure-extension-access --xformers --no-half --vae-dir <Models path>\VAE --ckpt-dir <Models path>\Stable-diffusion --lora-dir <Models path>\Lora
Using sqlite file: <AUTO1111-1.8-path>\webui\extensions\sd-webui-agent-scheduler\task_scheduler.sqlite3
ControlNet preprocessor location: <AUTO1111-1.8-path>\webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-16 20:42:43,150 - ControlNet - INFO - ControlNet v1.1.441
2024-03-16 20:42:44,356 - ControlNet - INFO - ControlNet v1.1.441
*** Error loading script: bop.py
    Traceback (most recent call last):
      File "<AUTO1111-1.8-path>\webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "<AUTO1111-1.8-path>\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\scripts\bop.py", line 1, in <module>
        from scripts.main_function import bop
      File "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\scripts\main_function.py", line 4, in <module>
        from Face_Detection.detect_all_dlib import detect
      File "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\Face_Detection\detect_all_dlib.py", line 18, in <module>
        import dlib
    ModuleNotFoundError: No module named 'dlib'

---
*** Error loading script: main_function.py
    Traceback (most recent call last):
      File "<AUTO1111-1.8-path>\webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "<AUTO1111-1.8-path>\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\scripts\main_function.py", line 4, in <module>
        from Face_Detection.detect_all_dlib import detect
      File "<AUTO1111-1.8-path>\webui\extensions\sd-webui-old-photo-restoration\Face_Detection\detect_all_dlib.py", line 18, in <module>
        import dlib
    ModuleNotFoundError: No module named 'dlib'

---
Loading weights [0724518c6b] from <Models path>\Stable-diffusion\SDXL 1.0\Juggernaut XL v7\juggernautXL_v7Rundiffusion.safetensors
Creating model from config: <AUTO1111-1.8-path>\webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
INFO:root:Loaded ViT-bigG-14 model config.
Loaded ViT-bigG-14 model config.

**Comment by Haoming02** [comment]
> ModuleNotFoundError: No module named '_socket'

iirc, tihs is caused by using the embedded python from Release. 
And the only way to solve it is by actually installing Python and clone the repo instead of using the Release.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12746

**Comment by itzolkmar** [comment]
OK. I understand. I tried and installed it successfully to a 1.7 install of Auto1111 which is using my original Python3-10 install. Thanks for the hint. :-)

**Comment by itzolkmar** [comment]
Reason was the use of the bundle version of Auto1111 V1.8. Using it with a "normal" install of V1.7 was succesful.
