### ISSUE TITLE
This extension will NOT install without MANY errors in Forge

### ISSUE THREAD

**Issue by MrMxyzptlk** [Haoming02/sd-webui-old-photo-restoration#15]
Installed with URL or from repository fails.

**Comment by Haoming02** [comment]
Please post the errors

**Comment by Fretag** [comment]
I installed it with forge. I don't get errors but I do not see the tab in the extras section.

**Comment by Haoming02** [comment]
Same as #5 then

**TL;DR:** 
1. Install VS 2022 C++
2. Install CMake
3. Download a pre-built package for `dlib`

**Comment by MrMxyzptlk** [comment]
Thank you!
