### ISSUE TITLE
Tried installing with no luck (errors below)

### ISSUE THREAD

**Issue by MxProteus** [Haoming02/sd-webui-old-photo-restoration#17]
[OldPhotorestoration_errorlog.txt](https://github.com/Haoming02/sd-webui-old-photo-restoration/files/14898779/OldPhotorestoration_errorlog.txt)

**Comment by MxProteus** [comment]
I did the install before reading the instructions on GIT, none of the files that had to be extracted were present until after running the install, not sure if that's what caused the error's or not. Once I remember what the command line is to tell Auto1111 to update extensions on boot I'll see if it fixes the problem.

**Comment by Haoming02** [comment]
If it's about `dlib`, then refer to #4 

**TL;DR:** 
1. Install VS 2022 C++
2. Install CMake
3. Download a pre-built package for `dlib`
