### ISSUE TITLE
6Gb Vram, does work?

### ISSUE THREAD

**Issue by AnyKillAtor** [Haoming02/sd-webui-old-photo-restoration#22]
I have a Laptop with 6gb Vram, I vram error, can I fix it?

**Comment by Haoming02** [comment]
Try editing this line

> https://github.com/Haoming02/sd-webui-old-photo-restoration/blob/main/scripts/main_function.py#L25

to:

```py
GPU_ID = -1
```

to run it on the CPU instead.
