### ISSUE TITLE
dlib is already installed, but the extension still doesn’t show up in Forge. 

### ISSUE THREAD

**Issue by Kimthanh27** [Haoming02/sd-webui-old-photo-restoration#24]
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> print(dlib.__version__)
19.24.1
>>>
Hi Haoming, I checked and dlib is already installed, but the extension still doesn’t show up in Forge. Does it support Forge?

**Comment by Haoming02** [comment]
Yes, it works on Forge.

Did you install the `dlib` package inside the virtual environment `venv` used by your WebUI?

**Comment by Haoming02** [comment]
If it still doesn't work, try installing `dlib-bin` instead~
