### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by Dintan** [Haoming02/sd-webui-old-photo-restoration#26]
If I want to use it through the api, what do I do
at the moment I have`{
  "resize_mode": 0,
  "show_extras_results": true,
  "gfpgan_visibility": 0,
  "codeformer_visibility": 0,
  "codeformer_weight": 0,
  "upscaling_resize": 4,
  "upscaling_resize_w": 512,
  "upscaling_resize_h": 512,
  "upscaling_crop": true,
  "upscaler_1": "None",
  "upscaler_2": "None",
  "extras_upscaler_2_visibility": 0,
  "upscale_first": false,
  "image": "",

  "extras": {
    "old_photo_restoration": true,
    "highres_fix": true,
    "process_scratch": true,
    "use_cpu": true,
    "restore_processing_order": "Restoration First"
  }
}
` but this doesnt call it

**Comment by Haoming02** [comment]
**API** is now supported~

Please use the `/bop` endpoint:

<p align="center"><img src="https://github.com/user-attachments/assets/125b4f57-e042-4ffc-896b-feb4742adeb7"></p>
