### ISSUE TITLE
not fully restoration

### ISSUE THREAD

**Issue by dongxiat** [Haoming02/sd-webui-old-photo-restoration#28]
![461705227_849133484003777_4722397437524860302_n](https://github.com/user-attachments/assets/6373de8e-401a-4d82-835e-ef981e770b2d)

https://github.com/user-attachments/assets/dbe4dd72-02f7-4fc6-86c1-dd24e5bbd973

i'm try this image

**Comment by Haoming02** [comment]
Welp, as this Extension is simply a wrapper, if it cannot process your image, I cannot help you either.

Try asking in the [original repo](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life) instead...
