### ISSUE TITLE
Support ComfyUI

### ISSUE THREAD

**Issue by villain535** [Haoming02/sd-webui-old-photo-restoration#6]
Hi!

Love this extension. Can you please make it available for ComfyUI?

**Comment by Haoming02** [comment]
For Automatic1111, at least it had an actual UI, and allows users to easily send images between tabs.

For ComfyUI... just clone the original repo, process the image, then load it in ComfyUI instead.

**Comment by villain535** [comment]
Thx for your suggestion. Actually, all i need is to get scratches data form Original model and deliver it to ComfyUI as mask.

How do you think is it possible to pack it into ComfyUI custom node?

**Comment by Haoming02** [comment]
In the original repo, it does indeed process the scratch into a black & white mask during the intermediate steps.

If you really want, I can probably write it next week *(on vaca rn)*

**Comment by villain535** [comment]
> If you really want, I can probably write it next week _(on vaca rn)_

Thank you so much! I believe that community would be happy to have such a custom node in ComfyUI than could reuse those intermediate steps as getting scratches as mask...

**Comment by Haoming02** [comment]
~~Half a year later~~...

https://github.com/Haoming02/comfyui-old-photo-restoration
