### ISSUE TITLE
A1111 v1.8

### ISSUE THREAD

**Issue by barepixels** [Haoming02/sd-webui-old-photo-restoration#8]
A1111 v1.8 change "outputs" to "output"

BOP is broken

**Comment by Haoming02** [comment]
Not really sure what you meant

But if you just want to change the folder *(which you can edit on the UI btw)*, open `ui-config.json` and change the `"sd-webui-old-photo-restoration/Output/value"` entry

**Comment by dlovep** [comment]
A1111 version: [1.8.0-RC] •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  
the BOP tab is not showing in any of the menu.

**Comment by Haoming02** [comment]
Any errors?

**Comment by dlovep** [comment]
> Any errors?

No error pop up , SD load up just fine.
![image](https://github.com/Haoming02/sd-webui-old-photo-restoration/assets/15388363/fb72bf2d-0054-4a7b-966b-e6fd5ce0919f)

**Comment by Haoming02** [comment]
Errr...
Why the heck does this happen...

You're the like the 3rd or 4th person to have this issue ( #5 )...

**Comment by Haoming02** [comment]
*(see above issue instead)*
