### ISSUE TITLE
suggestions.

### ISSUE THREAD

**Issue by zlzzzlll** [Haoming02/sd-webui-old-photo-restoration#9]
Hello, after a simple test, I have a few suggestions.
1. You can directly drag in pictures as input. and put the processed images into output
2. Add specified resolution options. There is almost no difference between the size of the processed image and the size before processing.
3. Add a function similar to ADetailer. In some photos, the face will become very blurry after processing.
4. Add the function of changing black and white pictures to color, similar to ioclab/control_v1p_sd15_brightness
Hope it gets better and better

**Comment by Haoming02** [comment]
1. Yeah. I'll probably move it into the `Extras` tab instead in the future. But this is not a high priority for me right now...
2. **Out of scope**. Use something else for upscaling.
3. There is already a Face Restoration option though?
4. **Out of scope**. I merely ported the original repo. If it doesn't do what you want, I can't help you either.
